import sqlite3
conn = sqlite3.connect("celebrities.db")
cursor = conn.cursor()
#data supplied as a tuple of tuples. / - placeholders for data
sql = "insert into celebs values (?,?,?,?,?,?,?)"
data = ( (1, "Angelina", "Jolie", 40, "angie@hollywood.us", "http://www.nphinity.com/pics/aj.jpg", "Angelina was born in Los Angeles, CA. She is the daughter of famous actor Jon Voight. In 2005, she met Brad Pitt on the set of Mr. and Mrs. Smith and married shortly after. They have a total of 6 kids together. They divorced in 2016."), (2, "Brad", "Pitt", 51, "brad@hollywood.us", "http://www.nphinity.com/pics/bp.jpg", "Brad was born in Oklahoma. He has been married twice, once with Jennifer Aniston, and once with Jolie. He has one brother named Douglas. Sadly him and Jolie are separated. He has won 61 awards in his career"), (3, "Snow", "White", 21, "sw@disney.org", "http://www.nphinity.com/pics/sw.jpg", "Snow white has seven small friends. She hates her stepmom. She once ate a bad apple and nearly died. She met her husband in the forest while passed out. They lived happily ever after."), (4, "Darth", "Vader", 29, "dv@darkside.me","http://www.nphinity.com/pics/dv.jpg", "Vader is the father of Luke Skywalker. He has not been the nicest guy. Also, He was previously known as Anakin Skywalker. Darth has appeared in 3 films. He is a human-Cyborg."), (5, "Taylor", "Swift", 25, "ts@1989.us", "http://www.nphinity.com/pics/ts.jpg", "Swift has 275 awards. She started as a country singer at the age of 14. Her songs now mostly consist of Pop. She cannot seem to keep a guy longer than a few months. Her net worth is $250 million."), (6, "Beyonce", "Knowles", 34, "beyonce@jayz.me", "http://www.nphinity.com/pics/bk.jpg", "Beyonce has slayed for many years. She has 224 awards. She is married to Jay-z. Her first child's name is Blue Ivy. She was once part of the group Destiny's Child."), (7, "Selena", "Gomez", 23, "selena@hollywood.us", "http://www.nphinity.com/pics/sg.jpg", "Selena Gomez was the star of Wizards of Waverly Place a few years ago. She started as an actress, then began singing. Her most recent love interest was Bieber. She is the most followed woman on instagram. She has around 100 million followers."), (8, "Stephen", "Curry", 27, "steph@golden.bb", "http://www.nphinity.com/pics/sc.jpg", "Stephen plays for the Golden State Warriors. He married to Ayesha. They have two daughters. He recent won the NBA championship. He is 6 foot 3 inches."))
cursor.executemany(sql, data)
#commit the changes
conn.commit()
conn.close()
